"use strict";
const $=id=>document.getElementById(id); let lastResult=null,lastSignal=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function focusRequest(){ $('request').focus(); $('request').scrollIntoView({behavior:'smooth',block:'center'}); }
function loadRequest(t){$('request').value=t;focusRequest();runRequest()}
function showCalc(id){document.querySelectorAll('.calc').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden')}
function clearWorkspace(){ $('request').value=''; $('taskBanner').className='hidden'; $('workspaceResult').innerHTML=''; lastResult=null; updateReport(); }
function classify(t){
 t=t.toLowerCase();
 if(/\b(square|sine|cosine|triangle|sawtooth|pulse|dc|noise)\s*(wave|waveform|signal)?\b/.test(t)||/waveform|signal generator|generate a signal/.test(t)) return 'signal';
 if(/voltage divider|divide.*voltage|5v.*3\.3|3\.3.*5v/.test(t)) return 'divider';
 if(/\bled\b/.test(t)) return 'led';
 if(/low.?pass|high.?pass|rc filter|filter/.test(t)) return 'rcfilter';
 if(/rlc|resonance|resonant frequency/.test(t)) return 'rlc';
 if(/ohm|current.*resistance|voltage.*current|power.*(volt|amp)|watts?/.test(t)) return 'ohm';
 if(/adc|dac|resolution.*bit|bits.*vref/.test(t)) return 'adc';
 if(/shannon|channel capacity|bandwidth.*snr/.test(t)) return 'comm';
 if(/binary|decimal|hex|octal|number system/.test(t)) return 'digital';
 if(/debug|not working|error|wrong output|fault/.test(t)) return 'debug';
 if(/software|proteus|multisim|ltspice|kicad|matlab|simulink|falstad/.test(t)&&/design|build|circuit|simulate|schematic/.test(t)) return 'software';
 if(/circuit|design|build|schematic|amplifier|rectifier|oscillator|regulator|counter|flip.?flop|mux|demux|arduino|uart|spi|i2c|pwm|sensor/.test(t)) return 'circuit';
 return 'general';
}
function extractNum(t,rx,def){const m=t.match(rx);return m?Number(m[1]):def}
function parseRequest(raw){const t=raw.toLowerCase(),type=classify(t); let result={type,title:'ECE Request',request:raw};
 if(type==='signal'){let wave=/square/.test(t)?'square':/triangle/.test(t)?'triangle':/sawtooth/.test(t)?'sawtooth':/cosine/.test(t)?'cosine':/pulse/.test(t)?'pulse':/noise/.test(t)?'noise':/dc\b/.test(t)?'dc':'sine';let f=extractNum(t,/([\d.]+)\s*(k|m|g)?\s*hz/i,1000);let fm=t.match(/[\d.]+\s*(k|m|g)?\s*hz/i); if(fm&&fm[1]){let u=(fm[1].toLowerCase()); f*=u==='k'?1e3:u==='m'?1e6:u==='g'?1e9:1;}let a=extractNum(t,/([\d.]+)\s*v(?:\s*(?:amplitude|peak))?/i,5); result.title='Signal Generator';result.wave=wave;result.params={f,a,phase:0,offset:0,duty:50,fs:Math.max(10000,10*f)}; result.html=signalUI(result);}
 else if(type==='divider'){let vin=extractNum(t,/([\d.]+)\s*v/,5),vout=extractNum(t,/([\d.]+)\s*v\s*(?:out|to)/,3.3);result.title='Voltage Divider Designer';result.params={vin,vout};result.html=dividerUI(result);}
 else if(type==='led'){result.title='LED Circuit Designer';result.html=ledUI(result);}
 else if(type==='rcfilter'){result.title='RC Low-Pass Filter';result.html=rcUI(result);}
 else if(type==='rlc'){result.title='RLC Resonance Calculator';result.html=rlcUI(result);}
 else if(type==='ohm'){result.title="Ohm's Law / Power";result.html=ohmUI(result);}
 else if(type==='adc'){result.title='ADC Resolution';result.html=adcUI(result);}
 else if(type==='comm'){result.title='Communication Calculator';result.html=commUI(result);}
 else if(type==='digital'){result.title='Digital Number System';result.html=digitalUI(result);}
 else if(type==='debug'){result.title='Debugging Assistant';result.html=debugUI(result);}
 else if(type==='software'){result.title='Software Circuit Design';result.html=softwareUI(result);}
 else if(type==='circuit'){result.title='Circuit Design Workspace';result.html=genericCircuitUI(result);}
 else {result.title='ECE Assistant';result.html=generalUI(result);}
 return result;
}
function banner(title,type){return `<div class="task"><b>${esc(title)}</b><br><span class="muted">Detected workflow: ${esc(type)}. Only relevant controls are shown.</span></div>`}
function runRequest(){const raw=$('request').value.trim();if(!raw){$('workspaceResult').innerHTML='<div class="warning">Tell me what you want to design, calculate, generate, analyze or debug.</div>';return}lastResult=parseRequest(raw);$('taskBanner').className='';$('taskBanner').innerHTML=banner(lastResult.title,lastResult.type);$('workspaceResult').innerHTML=lastResult.html;wireTask(lastResult);updateReport();$('workspaceResult').scrollIntoView({behavior:'smooth',block:'nearest'});}
function signalUI(r){return `<div class="result"><h3>Visual signal setup</h3><div class="grid"><label>Waveform<select id="taskWave"><option value="sine">Sine</option><option value="cosine">Cosine</option><option value="square">Square</option><option value="triangle">Triangle</option><option value="sawtooth">Sawtooth</option><option value="pulse">Pulse</option><option value="dc">DC</option><option value="noise">Noise</option></select></label><label>Frequency Hz<input id="taskF" type="number" step="any" value="${r.params.f}"></label><label>Amplitude<input id="taskA" type="number" step="any" value="${r.params.a}"></label><label>Phase °<input id="taskP" type="number" step="any" value="0"></label><label>Offset<input id="taskO" type="number" step="any" value="0"></label><label>Duty %<input id="taskD" type="number" step="any" value="50"></label><label>Sampling Hz<input id="taskFS" type="number" step="any" value="${r.params.fs}"></label></div><button onclick="generateTaskSignal()">Generate Visual Waveform</button><div id="taskSignalOut"></div></div>`}
function wireTask(r){if(r.type==='signal')$('taskWave').value=r.wave}
function generateTaskSignal(){const type=$('taskWave').value,f=Number($('taskF').value),a=Number($('taskA').value),ph=Number($('taskP').value)*Math.PI/180,o=Number($('taskO').value),d=Number($('taskD').value)/100,fs=Number($('taskFS').value);const msg=makeSignal(type,f,a,ph,o,d,fs);if(msg.error){$('taskSignalOut').innerHTML=`<div class="warning">${esc(msg.error)}</div>`;return}lastSignal=msg.signal;$('taskSignalOut').innerHTML=`<div class="metrics">${metric('Peak',msg.peak.toFixed(5))}${metric('RMS',msg.rms.toFixed(5))}${metric('Mean',msg.mean.toFixed(5))}${metric('Period',f>0?(1/f).toExponential(4):'—')}${metric('Status','Generated')}</div><canvas id="taskPlot" width="1100" height="340"></canvas><p class="muted">This is a browser-generated representation, not a physical measurement or SPICE simulation.</p>`;drawOn($('taskPlot'),msg.signal.t,msg.signal.y);lastResult.details={kind:'signal',data:msg};updateReport()}
function metric(k,v){return `<div><b>${esc(k)}</b>${esc(v)}</div>`}
function makeSignal(type,f,a,ph,o,d,fs){if(![f,a,ph,o,d,fs].every(Number.isFinite)||f<0||fs<=0||d<0||d>1)return {error:'Enter valid waveform parameters.'};if(f>0&&fs<2*f)return {error:'Sampling frequency must be at least 2× the signal frequency.'};const N=Math.max(200,Math.min(6000,Math.floor(fs*Math.max(.01,5/Math.max(f,1))))),t=[],y=[];for(let n=0;n<N;n++){let tt=n/fs,phase=2*Math.PI*f*tt+ph,cy=f?((f*tt+ph/(2*Math.PI))%1+1)%1:0,yy;if(type==='sine')yy=a*Math.sin(phase);else if(type==='cosine')yy=a*Math.cos(phase);else if(type==='square')yy=a*(Math.sin(phase)>=0?1:-1);else if(type==='triangle')yy=a*(2/Math.PI)*Math.asin(Math.sin(phase));else if(type==='sawtooth')yy=a*(2*cy-1);else if(type==='pulse')yy=cy<d?a:0;else if(type==='dc')yy=a;else yy=a*(2*Math.random()-1);t.push(tt);y.push(yy+o)}const peak=Math.max(...y.map(v=>Math.abs(v))),mean=y.reduce((s,v)=>s+v,0)/y.length,rms=Math.sqrt(y.reduce((s,v)=>s+v*v,0)/y.length);return {signal:{t,y,fs},peak,rms,mean}}
function drawOn(c,t,y){const x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.strokeStyle='#d9e2ec';x.lineWidth=1;for(let i=1;i<10;i++){x.beginPath();x.moveTo(i*w/10,0);x.lineTo(i*w/10,h);x.stroke()}for(let i=1;i<6;i++){x.beginPath();x.moveTo(0,i*h/6);x.lineTo(w,i*h/6);x.stroke()}let mn=Math.min(...y),mx=Math.max(...y),sp=mx-mn||1;x.strokeStyle='#2563eb';x.lineWidth=2;x.beginPath();y.forEach((v,i)=>{let px=i*w/(y.length-1),py=h-(v-mn)/sp*h;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.fillStyle='#334155';x.font='14px Arial';x.fillText('Amplitude / Voltage',12,20);x.fillText('Time',w-45,h-10)}
function dividerUI(r){let {vin,vout}=r.params;let ratio=vout/vin,r2=10000,r1=ratio>0&&ratio<1?r2*(1/ratio-1):10000;return `<div class="result"><h3>Design result</h3><p>Target: ${vin} V → ${vout} V. Using R2 = 10 kΩ, calculated R1 ≈ ${r1.toFixed(1)} Ω.</p>${dividerSVG(vin,vout,r1,r2)}<table class="connection"><tr><th>From</th><th>To</th><th>Component</th></tr><tr><td>Vin +</td><td>Vout node</td><td>R1 = ${r1.toFixed(1)} Ω</td></tr><tr><td>Vout node</td><td>GND</td><td>R2 = ${r2} Ω</td></tr></table><p><b>Formula:</b> Vout = Vin × R2 / (R1 + R2)</p><h3>Hardware rig-up</h3><ol class="steps"><li>Place R1 between Vin and the Vout node.</li><li>Place R2 between Vout and GND.</li><li>Connect the source negative terminal to GND.</li><li>Measure Vout with respect to GND before connecting a load.</li><li>Remember: a simple divider is load-dependent; it is not a regulated supply.</li></ol><h3>Software visual / simulation setup</h3><ol class="steps"><li>Open your chosen circuit simulator.</li><li>Place a DC source, two resistors and ground.</li><li>Set R1 and R2 to the displayed values.</li><li>Wire source → R1 → Vout → R2 → ground.</li><li>Add a voltage probe at Vout and run the DC operating-point/transient analysis available in that tool.</li><li>Compare the simulated Vout with the calculated value. AutoCircuit does not claim that the external simulation was actually run.</li></ol></div>`}
function dividerSVG(vin,vo,r1,r2){return `<svg class="schematic" viewBox="0 0 820 360" xmlns="http://www.w3.org/2000/svg"><g stroke="#152033" stroke-width="3" fill="none"><line x1="200" y1="30" x2="200" y2="90"/><rect x="175" y="90" width="50" height="75"/><line x1="200" y1="165" x2="200" y2="205"/><rect x="175" y="205" width="50" height="75"/><line x1="200" y1="280" x2="200" y2="320"/><line x1="200" y1="180" x2="470" y2="180"/><line x1="470" y1="180" x2="470" y2="230"/><line x1="450" y1="230" x2="490" y2="230"/><line x1="455" y1="242" x2="485" y2="242"/></g><g font-family="Arial" font-size="18" fill="#152033"><text x="105" y="55">Vin = ${vin} V</text><text x="240" y="130">R1 = ${r1.toFixed(1)} Ω</text><text x="240" y="250">R2 = ${r2} Ω</text><text x="495" y="185">Vout ≈ ${vo} V</text><text x="155" y="345">GND</text></g></svg>`}
function ledUI(){return `<div class="result"><h3>LED + current-limiting resistor</h3><p>Visual topology: Supply → resistor → LED → GND.</p><svg class="schematic" viewBox="0 0 800 280"><g stroke="#152033" stroke-width="3" fill="none"><line x1="160" y1="35" x2="160" y2="85"/><rect x="135" y="85" width="50" height="70"/><line x1="160" y1="155" x2="160" y2="205"/><path d="M135 205 L185 205 L160 245 Z"/><line x1="160" y1="245" x2="160" y2="260"/></g><g font-family="Arial" font-size="18" fill="#152033"><text x="100" y="28">SUPPLY</text><text x="205" y="125">Rlim</text><text x="205" y="225">LED</text><text x="100" y="275">GND</text></g></svg><h3>Rig-up steps</h3><ol class="steps"><li>Identify LED anode and cathode.</li><li>Connect the resistor in series with the LED.</li><li>Connect the series path to the supply and GND.</li><li>Use the LED forward-voltage and target-current values to calculate R = (Vs − Vf)/I.</li><li>Check resistor power P = I²R before powering the circuit.</li></ol><p class="muted">Component values cannot be finalized accurately without supply voltage, LED Vf and target current.</p></div>`}
function rcUI(){return `<div class="result"><h3>RC low-pass visual</h3><svg class="schematic" viewBox="0 0 850 300"><g stroke="#152033" stroke-width="3" fill="none"><line x1="50" y1="120" x2="180" y2="120"/><rect x="180" y="90" width="90" height="60"/><line x1="270" y1="120" x2="430" y2="120"/><line x1="430" y1="120" x2="430" y2="180"/><line x1="400" y1="180" x2="460" y2="180"/><line x1="405" y1="195" x2="455" y2="195"/><line x1="430" y1="195" x2="430" y2="250"/><line x1="430" y1="250" x2="430" y2="265"/></g><g font-family="Arial" font-size="18"><text x="55" y="105">Vin</text><text x="205" y="125">R</text><text x="445" y="125">Vout</text><text x="445" y="205">C</text><text x="395" y="285">GND</text></g></svg><p>Cutoff frequency: fc = 1/(2πRC).</p><h3>Software setup steps</h3><ol class="steps"><li>Place AC source, resistor, capacitor and ground.</li><li>Wire the source through R to the output node.</li><li>Connect C from output to ground.</li><li>Set a transient or AC sweep according to the simulator.</li><li>Probe Vin and Vout and inspect attenuation around fc.</li></ol></div>`}
function rlcUI(){return `<div class="result"><p>Enter L and C below to calculate resonant frequency.</p><div class="grid"><label>L (H)<input id="taskL" value="0.001" type="number" step="any"></label><label>C (F)<input id="taskC" value="0.000001" type="number" step="any"></label></div><button onclick="taskRLC()">Calculate Resonance</button><div id="taskRLCOut" class="answer"></div></div>`}
function taskRLC(){let l=Number($('taskL').value),c=Number($('taskC').value);if(l<=0||c<=0||!Number.isFinite(l)||!Number.isFinite(c))return $('taskRLCOut').textContent='L and C must be positive.';let f=1/(2*Math.PI*Math.sqrt(l*c));$('taskRLCOut').innerHTML=`f₀ = ${f.toFixed(6)} Hz<br><span class="muted">Status: Calculated</span>`;lastResult.details={kind:'calculation',content:$('taskRLCOut').innerText};updateReport()}
function ohmUI(){return `<div class="result"><div class="grid"><label>Voltage V<input id="taskOV"></label><label>Current A<input id="taskOI"></label><label>Resistance Ω<input id="taskOR"></label></div><button onclick="taskOhm()">Calculate Missing Value</button><div id="taskOhmOut" class="answer"></div></div>`}
function taskOhm(){let v=$('taskOV').value.trim(),i=$('taskOI').value.trim(),r=$('taskOR').value.trim(),a=[v,i,r].map(x=>x===''?NaN:Number(x));if(a.filter(Number.isFinite).length!==2)return $('taskOhmOut').textContent='Enter exactly two values.';[v,i,r]=a;if(!Number.isFinite(v))v=i*r;if(!Number.isFinite(i))i=r===0?NaN:v/r;if(!Number.isFinite(r))r=i===0?NaN:v/i;if(![v,i,r].every(Number.isFinite))return $('taskOhmOut').textContent='Undefined result.';$('taskOhmOut').innerHTML=`V = ${v} V<br>I = ${i} A<br>R = ${r} Ω<br><span class="muted">Status: Calculated</span>`;lastResult.details={kind:'calculation',content:$('taskOhmOut').innerText};updateReport()}
function adcUI(){return `<div class="result"><div class="grid"><label>Bits<input id="taskBits" value="12" type="number"></label><label>Vref<input id="taskVref" value="3.3" type="number" step="any"></label></div><button onclick="taskADC()">Calculate</button><div id="taskADCOut" class="answer"></div></div>`}
function taskADC(){let b=Number($('taskBits').value),v=Number($('taskVref').value);if(!Number.isInteger(b)||b<1||b>32||v<=0)return $('taskADCOut').textContent='Use 1–32 bits and positive Vref.';let levels=2**b,lsb=v/levels;$('taskADCOut').innerHTML=`Levels = ${levels}<br>Ideal LSB ≈ ${lsb.toExponential(6)} V<br>Full-scale code = ${levels-1}<br><span class="muted">Status: Calculated</span>`;lastResult.details={kind:'calculation',content:$('taskADCOut').innerText};updateReport()}
function commUI(){return `<div class="result"><div class="grid"><label>Bandwidth Hz<input id="taskBW" value="1000000" type="number"></label><label>SNR linear<input id="taskSNR" value="10" type="number" step="any"></label></div><button onclick="taskComm()">Calculate</button><div id="taskCommOut" class="answer"></div></div>`}
function taskComm(){let b=Number($('taskBW').value),s=Number($('taskSNR').value);if(b<=0||s<0)return $('taskCommOut').textContent='Bandwidth must be > 0 and SNR ≥ 0.';let c=b*Math.log2(1+s);$('taskCommOut').innerHTML=`C = ${c.toFixed(3)} bit/s<br><span class="muted">Status: Calculated</span>`;lastResult.details={kind:'calculation',content:$('taskCommOut').innerText};updateReport()}
function digitalUI(){return `<div class="result"><div class="grid"><label>Number<input id="taskNum" value="42"></label><label>Base<select id="taskBase"><option value="10">Decimal</option><option value="2">Binary</option><option value="8">Octal</option><option value="16">Hex</option></select></label></div><button onclick="taskDigital()">Convert</button><div id="taskDigitalOut" class="answer"></div></div>`}
function taskDigital(){let raw=$('taskNum').value.trim(),base=Number($('taskBase').value),n=parseInt(raw,base);if(Number.isNaN(n))return $('taskDigitalOut').textContent='Invalid number.';$('taskDigitalOut').textContent=`Binary: ${n.toString(2)} • Decimal: ${n} • Octal: ${n.toString(8)} • Hex: ${n.toString(16).toUpperCase()}`;lastResult.details={kind:'calculation',content:$('taskDigitalOut').innerText};updateReport()}
function softwareUI(){return `<div class="result"><h3>Software-design workflow</h3><p>The request indicates that you want a simulator/software representation. Choose a simulator only for the setup instructions below; AutoCircuit does not pretend to launch external software from GitHub Pages.</p><div class="grid"><label>Tool for your rig-up<select id="simTool"><option>Proteus</option><option>LTspice</option><option>NI Multisim</option><option>KiCad</option><option>Falstad</option><option>MATLAB / Simulink</option></select></label></div><h3>Visual representation</h3><div class="warning">A task-specific schematic/visual is generated when the circuit type and values are known. For an unspecified circuit, first provide the function, input/supply, output/load and important constraints.</div><h3>Software rig-up steps</h3><ol class="steps"><li>Open the selected simulator and create a new schematic/project.</li><li>Place the components shown in the AutoCircuit visual representation.</li><li>Set each component value exactly as listed.</li><li>Wire every node according to the connection table and connect the correct ground/reference.</li><li>Set source, analysis type and simulation time/frequency according to the requested behavior.</li><li>Run the simulator and inspect probes/oscilloscope/waveforms.</li><li>Compare the simulated output with AutoCircuit's calculated/expected result.</li></ol><p class="muted">External software execution is not performed by this static GitHub Pages build.</p></div>`}
function genericCircuitUI(){return `<div class="result"><h3>What I need to design this accurately</h3><div class="grid"><label>Function / goal<input id="gcGoal" placeholder="e.g. amplify a 1 kHz signal"></label><label>Supply<input id="gcSupply" placeholder="e.g. 5 V single supply"></label><label>Input / load<input id="gcLoad" placeholder="e.g. 10 kΩ load"></label></div><button onclick="genericDesign()">Generate Design Brief</button><div id="gcOut"></div></div>`}
function genericDesign(){$('gcOut').innerHTML='<h3>Design brief</h3><p>Use the entered function, supply and load to create the circuit topology, component calculations, schematic, connection table, software rig-up steps, hardware rig-up steps and expected outputs. This browser-only build will not claim an external simulator run.</p>'}
function debugUI(){return `<div class="result"><h3>Debugging Assistant</h3><p>Upload/paste a screenshot or describe the symptom in the request. The browser-only build can provide structured troubleshooting guidance, but it will not claim certainty without evidence.</p><h3>Checklist</h3><ol class="steps"><li>Check supply voltage and polarity.</li><li>Check common ground/reference.</li><li>Check component orientation and pin numbering.</li><li>Check for floating nodes or unintended shorts.</li><li>Check ratings and expected operating range.</li><li>Compare measured/observed waveform against the expected waveform.</li></ol></div>`}
function generalUI(){return `<div class="result"><p>Describe the ECE goal more specifically—for example, design, calculate, generate a waveform, analyze a signal, debug a circuit, or create a lab experiment.</p></div>`}
function scientific(){let raw=$('expr').value.trim();try{let s=raw.replace(/×/g,'*').replace(/÷/g,'/').replace(/π/g,'pi').replace(/\^/g,'**');if(!/^[0-9+\-*/().,_\sA-Za-z*]+$/.test(s))throw 0;let deg=$('angle').value==='deg',env={pi:Math.PI,e:Math.E,sqrt:Math.sqrt,log:Math.log10,ln:Math.log,exp:Math.exp,abs:Math.abs,sin:x=>Math.sin(deg?x*Math.PI/180:x),cos:x=>Math.cos(deg?x*Math.PI/180:x),tan:x=>Math.tan(deg?x*Math.PI/180:x)};let z=new Function(...Object.keys(env),`"use strict";return (${s})`)(...Object.values(env));if(!Number.isFinite(z))throw 0;$('sciAns').textContent=z}catch{$('sciAns').textContent='Invalid expression.'}}
function ohm(){let a=[$('ov').value,$('oi').value,$('or').value].map(x=>x===''?NaN:Number(x));if(a.filter(Number.isFinite).length!==2)return $('ohmAns').textContent='Enter exactly two values.';let[v,i,r]=a;if(!Number.isFinite(v))v=i*r;if(!Number.isFinite(i))i=v/r;if(!Number.isFinite(r))r=v/i;$('ohmAns').textContent=`V = ${v} V • I = ${i} A • R = ${r} Ω`}
function powerCalc(){let v=Number($('pv').value),i=Number($('pii').value);$('powerAns').textContent=Number.isFinite(v)&&Number.isFinite(i)?`P = ${(v*i).toFixed(6)} W`:'Enter valid values.'}
const units={V:['Voltage',1],mV:['Voltage',1e-3],kV:['Voltage',1e3],A:['Current',1],mA:['Current',1e-3],uA:['Current',1e-6],ohm:['Resistance',1],kohm:['Resistance',1e3],Mohm:['Resistance',1e6],F:['Capacitance',1],uF:['Capacitance',1e-6],nF:['Capacitance',1e-9],pF:['Capacitance',1e-12],H:['Inductance',1],mH:['Inductance',1e-3],uH:['Inductance',1e-6],Hz:['Frequency',1],kHz:['Frequency',1e3],MHz:['Frequency',1e6],GHz:['Frequency',1e9],s:['Time',1],ms:['Time',1e-3],us:['Time',1e-6],ns:['Time',1e-9]};
function initUnits(){let o=Object.keys(units).map(k=>`<option>${k}</option>`).join('');$('uf').innerHTML=o;$('ut').innerHTML=o;$('ut').value='mV'}function convert(){let v=Number($('uv').value),a=$('uf').value,b=$('ut').value;if(!Number.isFinite(v)||units[a][0]!==units[b][0])return $('unitAns').textContent='Use valid values and compatible units.';$('unitAns').textContent=`${v} ${a} = ${v*units[a][1]/units[b][1]} ${b}`}
function acCalc(){let p=Number($('acp').value),f=Number($('acf').value);$('acAns').textContent=p>=0&&f>0?`RMS = ${(p/Math.sqrt(2)).toFixed(6)} V • Period = ${(1/f).toExponential(6)} s • ω = ${(2*Math.PI*f).toFixed(3)} rad/s`:'Enter valid values.'}function rlcCalc(){let l=Number($('rl').value),c=Number($('rc').value);$('rlcAns').textContent=l>0&&c>0?`f₀ = ${(1/(2*Math.PI*Math.sqrt(l*c))).toFixed(6)} Hz`:'L and C must be positive.'}function numberConvert(){let n=parseInt($('num').value.trim(),Number($('base').value));$('numAns').textContent=Number.isNaN(n)?'Invalid number.':`Binary: ${n.toString(2)} • Decimal: ${n} • Octal: ${n.toString(8)} • Hex: ${n.toString(16).toUpperCase()}`}function adcCalc(){let b=Number($('bits').value),v=Number($('vref').value);$('adcAns').textContent=b>=1&&b<=32&&v>0?`Levels = ${2**b} • Ideal LSB = ${(v/(2**b)).toExponential(6)} V`:'Enter valid values.'}function shannon(){let b=Number($('bw').value),s=Number($('snr').value);$('shannonAns').textContent=b>0&&s>=0?`C = ${(b*Math.log2(1+s)).toFixed(3)} bit/s`:'Enter valid values.'}
function generateSignal(){let r=makeSignal($('wt').value,Number($('wf').value),Number($('wa').value),Number($('wph').value)*Math.PI/180,Number($('wo').value),Number($('wd').value)/100,Number($('ws').value));if(r.error)return $('metrics').innerHTML=`<div class="warning">${esc(r.error)}</div>`;lastSignal=r.signal;$('metrics').innerHTML=metric('Peak',r.peak.toFixed(5))+metric('RMS',r.rms.toFixed(5))+metric('Mean',r.mean.toFixed(5))+metric('Samples',r.signal.y.length)+metric('Status','Generated');drawOn($('plot'),r.signal.t,r.signal.y)}
function downloadCSV(){if(!lastSignal)return alert('Generate a waveform first.');let csv='time_s,value\n'+lastSignal.t.map((v,i)=>`${v},${lastSignal.y[i]}`).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='autocircuit-waveform.csv';a.click()}
function reportData(){let req=$('request').value.trim(),title=lastResult?.title||'ECE Result',body='';if(lastResult?.details?.kind==='signal')body=`Signal parameters and generated waveform metrics:\n${$('taskSignalOut')?.innerText||''}`;else body=lastResult?.details?.content||$('workspaceResult').innerText||'No result yet.';return {name:$('reportName').value||'AutoCircuit ECE Result',req,title,body}}
function updateReport(){let d=reportData();$('reportPreview').innerHTML=`<h1>${esc(d.name)}</h1><p class="report-meta">AutoCircuit ECE • ${new Date().toLocaleString()}</p><h2>Aim / Request</h2><p>${esc(d.req||'—')}</p><h2>${esc(d.title)}</h2><pre>${esc(d.body)}</pre><p class="muted">Values in this report are browser-generated calculations/representations unless explicitly labelled otherwise. No external simulator or hardware measurement is claimed.</p>`}
function printReport(){updateReport();let p=window.open('','_blank');if(!p)return alert('Allow pop-ups for report printing.');p.document.write(`<!doctype html><html><head><title>${esc($('reportName').value||'AutoCircuit ECE Result')}</title><style>body{font-family:Arial;margin:40px;color:#111;line-height:1.5}h1{font-size:26px}h2{border-bottom:1px solid #ddd;padding-bottom:5px}pre{white-space:pre-wrap;background:#f5f5f5;padding:12px}small{color:#666}</style></head><body>${$('reportPreview').innerHTML}</body></html>`);p.document.close();p.focus();setTimeout(()=>p.print(),250)}
function exportReport(){let fmt=$('reportFormat').value;if(fmt==='pdf')return printReport();let d=reportData(),html=`<html><head><meta charset="utf-8"><title>${esc(d.name)}</title></head><body><h1>${esc(d.name)}</h1><p>AutoCircuit ECE • ${new Date().toLocaleString()}</p><h2>Aim / Request</h2><p>${esc(d.req)}</p><h2>${esc(d.title)}</h2><pre>${esc(d.body)}</pre><p>Browser-generated result; no external simulation or hardware measurement is claimed.</p></body></html>`;let blob=new Blob([html],{type:'application/msword'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=d.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.doc';a.click()}
initUnits();showCalc('sci');
